### ISSUE TITLE
defaultCountryiso parameter doesn't work 

### ISSUE THREAD

**Issue by thealiano** [azzamasghar1/ion-intl-tel-input#17]
Hello, 
It's seems that all the parameters working well except the defaultCountryiso 
```

 <ion-intl-tel-input 
                  modalTitle="Sélectionnez un pays"
                  modalSearchPlaceholder="Entrez le nom du pays"
                  modalCloseText="X"
                  modalSearchFailText="Pas de pays correspondant"
                  inputPlaceholder="votre numéro de téléphone"  
                  [defaultCountryiso]="countryDefault"
                  [preferredCountries]="preferredCountries"
                  selectFirstCountry="true"
                  formControlName="phoneNumber">
                  </ion-intl-tel-input>

`
```
Tried with : 
`  countryDefault= ["ch"];`    
`  countryDefault= 'ch';`    

Even with ` defaultCountryiso= 'ch'`     
The problems seems to be with the binding also they are several log in the console which suggest that:
```
write value
vendor.js:103703 null
vendor.js:103727 do
vendor.js:104233 set value
vendor.js:104234 value: Object
vendor.js:101340 Object
vendor.js:103902 on number change
vendor.js:104233 set value
vendor.js:104234 value: null
vendor.js:101340 null 
```

My current workaround with reactive form is to do that : 
```
..
phoneNumber: new FormControl(
            {
                internationalNumber: '',
                nationalNumber: '',
                isoCode: 'ch'
            }, [
            Validators.required,
            IonIntlTelInputValidators.phone
          ]),
..
```
 It's working but not optimal.

**Comment by azzamasghar1** [comment]
`defaultCountryiso ` is only used when you do not pass an initial value to the control. 

if you pass a default value to control like you did here 
`phoneNumber: new FormControl(
            {
                internationalNumber: '',
                nationalNumber: '',
                isoCode: 'ch'
            }, [
            Validators.required,
            IonIntlTelInputValidators.phone
          ]),`

Than this value will always overwrite the `defaultCountryiso` parameter.
