### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by azphelcc** [azzamasghar1/ion-intl-tel-input#18]
Hi. Good day!

Encountered a problem when running the app with the installed package. :( 
for some reason got an error saying ` TypeError: Object(...) is not a function`

but the problem seems to go away when we commented this line
`/** @nocollapse */ IonIntlTelInputService.ngInjectableDef = ɵɵdefineInjectable({ factory: function IonIntlTelInputService_Factory() { return new IonIntlTelInputService(); }, token: IonIntlTelInputService, providedIn: "root" });`
from `..node_modules/ion-intl-tel-input/fesm5/ion-intl-tel-input.js` line 2182

is there a way to fix this?
hoping to use this package because it's so simple, consists many features and it's using ionic-selectable 🙇
thanksssss 🙇

**Comment by azphelcc** [comment]
ohh I think it''s because of this "export 'ɵɵdefineInjectable' was not found in '@angular/core'"
sorry for the hassle 🙇

**Comment by azzamasghar1** [comment]
Glad you could fix it. Ping me up for any nee issue you might face.
