### ISSUE TITLE
Alignment Issue

### ISSUE THREAD

**Issue by reachsofi** [azzamasghar1/ion-intl-tel-input#19]
The design of Country Codes is not aligned with the input. I tried changing it by adding specificity to the classes of each element but it doesn't work. Is there any way this can be overwritten?
<img width="292" alt="Screen Shot 2021-07-12 at 8 55 19 PM" src="https://user-images.githubusercontent.com/24669249/125326787-79c9ef80-e353-11eb-9527-4b31ba4f994d.png">

**Comment by azzamasghar1** [comment]
Do you have a custom height on your input???

**Comment by reachsofi** [comment]
Yes a line height

**Comment by azzamasghar1** [comment]
Not related to this. More of a css issue.
