### ISSUE TITLE
Dirty Console

### ISSUE THREAD

**Issue by danilocastelhano1** [azzamasghar1/ion-intl-tel-input#23]
Hi guys, I'm using this amazing component, and its work as it should, but my console gets dirty every time, could you remove the logs?

![image](https://user-images.githubusercontent.com/52941839/131843520-66505e84-aba3-4113-b064-2787cda442e2.png)

Thanks

**Comment by azzamasghar1** [comment]
Hi, Yeah sorry about that. I will remove them in the next release ASAP.

**Comment by danilocastelhano1** [comment]
they'll remove the logs in the next version
