### ISSUE TITLE
Select all, cut, copy, paste via keyboard doesn't work

### ISSUE THREAD

**Issue by shianadela** [azzamasghar1/ion-intl-tel-input#26]
Hello, it seems keyboard shortcut for copy, paste, cut, and select all doesn't work in this component.

I tried to bypass the actions by css declaration as seen https://pretagteam.com/question/how-to-allow-text-to-be-copied-in-an-input-element-ionic but it's not working as well (note: this is using `ion-input`)

# Steps to replicate 
- in your `ion-intl-tel-input` component, do copy/paste/select all/cut using keyboard shortcut (ctrl/cmd + c/v/a/x)

# Demo
----
- **test from laptop:**
- manual copy+paste (ctrl + c ; ctrl + v) from keyboard (laptop/pc/machine) is not allowed 
- but using right mouse click and doing copy/select/cut/paste from there is allowed	
- https://user-images.githubusercontent.com/23480890/136506041-194d6c94-b250-4426-948e-58a84b3af5c8.mov

- **specs:**
```
    - model: MacBook Pro (Retina, 13-inch, Mid 2014)
    - os: macOS Big Sur (Version 11.5.1)
    - browser: Google Chrome (Version 94.0.4606.71)
```
----

- **test from phone:**
- only way to copy+paste is by selecting the input, which is working as expected
- https://user-images.githubusercontent.com/23480890/136504750-2b52ad8f-c01c-42c9-8d31-1e73778200c4.mov

- **specs:**
```
    - model: iPhone 11 
    - browser: safari v14.6
```

**Comment by jadurani** [comment]
"tab" also doesn't work
