### ISSUE TITLE
No API to remove a spaces between a mobile number

### ISSUE THREAD

**Issue by ksspam** [azzamasghar1/ion-intl-tel-input#32]
### Plugin not has an api to format a mobilenumber.
![Screenshot from 2021-12-06 19-43-22 Edited](https://user-images.githubusercontent.com/25908787/144862313-2b9bec83-32b3-4703-938d-d6a25171d914.png)
If anyone has any ideas. please comment below!

**Comment by azzamasghar1** [comment]
What kind of formatting do you need?

**Comment by azzamasghar1** [comment]
Currently numbers are being formatted by [google lib phonenumber](https://www.npmjs.com/package/google-libphonenumber). I can look into turning it off with a parameter maybe.

**Comment by ksspam** [comment]
> Currently numbers are being formatted by [google lib phonenumber](https://www.npmjs.com/package/google-libphonenumber). I can look into turning it off with a parameter maybe.

thanks for the reply! How?

**Comment by azzamasghar1** [comment]
There isn't anything in the lib that you can use to turn it off at the moment. It formats every number by default. Someone would have to add the functionality in the lib for this.

**Comment by ksspam** [comment]
Okay! Thanks! I will try!
But awesome plugin! Good work!
