### ISSUE TITLE
Do you know some jquery script which work like this script?

### ISSUE THREAD

**Issue by stojankukrika** [azzamasghar1/ion-intl-tel-input#53]
I ask this because when I enter the phone numbers on my ionic mobile apps works well but when I enter it on desktop/jquery I didn't get the same result. 
For example on Ionic app I get this:
` {"internationalNumber":"+387 30 212-344","nationalNumber":"030 212-344","isoCode":"ba","dialCode":"+387"}`
and on jquery(https://www.npmjs.com/package/intl-tel-input), I get only `+38730212344` and I am not sure how to make it both work in one way. Can you help me?

**Comment by hjalil8** [comment]
Its not really designed to work with jquery. I meant to only create this or ionic and even there only for angular. You can maybe look at the code and see if you can handle this on a fork.

**Comment by azzamasghar1** [comment]
Its not really designed to work with jquery. I meant to only create this or ionic and even there only for angular. You can maybe look at the code and see if you can handle this on a fork.
